spring:
  application:
    name: user-center


  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yun_you
    username: root
    password: 123456

  # Session Config
  session:
    timeout: 86400
